# Generated by Django 5.1.7 on 2025-04-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganization',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
