# Generated by Django 5.1.7 on 2025-04-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_userorganization_last_accessed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganization',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
